name: Jest

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches:
      - main
      - devel
  push:
    branches:
      - main
      - devel

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  Lint:
    # Name the Job
    name: Jest tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install npm packages
        run: npm install
      - name: Module tests
        run: npm run test:module
      - name: Snapshot tests
        run: npm run test:snapshot
